name: "FDO Device"
version: "1.0.0"
slug: "fdo_device"
description: "FDO Device running as a Home Assistant Add-on POWERED BY UMU"
arch:
  - aarch64
  - amd64
startup: application
boot: auto
map:
  - "config:rw"
  - "share:rw"
options:
  mud_url: "477ac7cd-c71e-444a-a124-f80c2f47393b"
  di_url: "http://192.168.0.181:8080"
  reset_credentials: false
schema:
  mud_url: str
  di_url: str
  reset_credentials: bool
